// <auto-generated />
using System;
using Canchas4.Datos;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Canchas4.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20221118002846_creamosCanchafutCanchavolei")]
    partial class creamosCanchafutCanchavolei
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("Canchas4.Models.CanchaFut", b =>
                {
                    b.Property<int>("CanchaFutId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CanchaFutId"), 1L, 1);

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("SedeId")
                        .HasColumnType("int");

                    b.HasKey("CanchaFutId");

                    b.HasIndex("SedeId");

                    b.ToTable("CanchaFut");
                });

            modelBuilder.Entity("Canchas4.Models.CanchVolei", b =>
                {
                    b.Property<int>("CanchaVoleiId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CanchaVoleiId"), 1L, 1);

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("SedeId")
                        .HasColumnType("int");

                    b.HasKey("CanchaVoleiId");

                    b.HasIndex("SedeId");

                    b.ToTable("CanchVolei");
                });

            modelBuilder.Entity("Canchas4.Models.Sede", b =>
                {
                    b.Property<int>("SedeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("SedeId"), 1L, 1);

                    b.Property<string>("Direccion")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Nombre")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("SedeId");

                    b.ToTable("Sede");
                });

            modelBuilder.Entity("Canchas4.Models.CanchaFut", b =>
                {
                    b.HasOne("Canchas4.Models.Sede", "Sede")
                        .WithMany("CanchaFut")
                        .HasForeignKey("SedeId");

                    b.Navigation("Sede");
                });

            modelBuilder.Entity("Canchas4.Models.CanchVolei", b =>
                {
                    b.HasOne("Canchas4.Models.Sede", "Sede")
                        .WithMany("CanchVolei")
                        .HasForeignKey("SedeId");

                    b.Navigation("Sede");
                });

            modelBuilder.Entity("Canchas4.Models.Sede", b =>
                {
                    b.Navigation("CanchVolei");

                    b.Navigation("CanchaFut");
                });
#pragma warning restore 612, 618
        }
    }
}
